### ISSUE TITLE
Can't run prediction, error in one_hot_enc function

### ISSUE THREAD

**Issue by faricazjj** [OrensteinLab/rG4detector#1]
Hi, I'm trying to run rG4detector to get the rG4 propensity per sequence but encountered an error.

**Background**
Here are the steps I did:

1. I created a fasta file  with the following sequences as the first two in the file as examples:
```
>0
GCAGCTGGTCACCAGTCTCTGAGGGCACCTCATGGACCAGGGGCTGGTGGCCCAGGCCAGGGAGGGAACCCTGGGCAGGGCTCTGGTGGGAGAGGGAGACAGATGGAGGCAGTGGCTGGTGGGCCACTCTCTCCAGGTG
>1
GGCGGAGGGCAAGTAGCAAGGGGGCGGGGTGTGGCCGCCGGAAGCCTAGCCGCTGCTCGGGGGGGACCTGCGGGCTCAGGCCCGGG
```

2. I then ran using the following command following the readme instructions:
```
python code/predict_fasta.py -f input.fa -o out
```

**Issue**
However, I get the following error message:
<img width="1050" alt="Screen Shot 2022-12-12 at 6 15 13 PM" src="https://user-images.githubusercontent.com/25573986/207179076-e79be954-a501-466a-8fbe-bf1d5a41b98c.png">

**Comment by maorturn** [comment]
Hi Farica,
Thank you so much, the bug was fixed. 
Let us know if you need any support or if you encounter any other difficulties
